const typescriptRules = {
  '@typescript-eslint/adjacent-overload-signatures': 2,
  '@typescript-eslint/ban-ts-comment': 1,
  '@typescript-eslint/ban-types': 2,
  '@typescript-eslint/brace-style': 0,
  '@typescript-eslint/camelcase': 0,
  '@typescript-eslint/comma-spacing': 0,
  '@typescript-eslint/explicit-module-boundary-types': 2,
  '@typescript-eslint/func-call-spacing': 0,
  '@typescript-eslint/indent': 0,
  '@typescript-eslint/keyword-spacing': 0,
  '@typescript-eslint/member-delimiter-style': 0,
  '@typescript-eslint/no-array-constructor': 2,
  '@typescript-eslint/no-empty-function': 2,
  '@typescript-eslint/no-empty-interface': 2,
  '@typescript-eslint/no-explicit-any': 1,
  '@typescript-eslint/no-extra-non-null-assertion': 2,
  '@typescript-eslint/no-extra-parens': 0,
  '@typescript-eslint/no-extra-semi': 0,
  '@typescript-eslint/no-inferrable-types': 2,
  '@typescript-eslint/no-misused-new': 2,
  '@typescript-eslint/no-namespace': 2,
  '@typescript-eslint/no-non-null-asserted-optional-chain': 2,
  '@typescript-eslint/no-non-null-assertion': 1,
  '@typescript-eslint/no-this-alias': 2,
  '@typescript-eslint/no-unused-vars': 1,
  '@typescript-eslint/no-var-requires': 2,
  '@typescript-eslint/prefer-as-const': 2,
  '@typescript-eslint/prefer-namespace-keyword': 2,
  '@typescript-eslint/quotes': 0,
  '@typescript-eslint/semi': 0,
  '@typescript-eslint/space-before-function-paren': 0,
  '@typescript-eslint/triple-slash-reference': 2,
  '@typescript-eslint/type-annotation-spacing': 0,
};

module.exports = typescriptRules;
