const disabledEslintRules = {
  'default-param-last': 0,
  'init-declarations': 0,
  'lines-between-class-members': 0,
  'no-array-constructor': 0,
  'no-dupe-class-members': 0,
  'no-duplicate-imports': 0,
  'no-empty-function': 0,
  'no-invalid-this': 0,
  'no-loop-func': 0,
  'no-loss-of-precision': 0,
  'no-magic-numbers': 0,
  'no-redeclare': 0,
  'no-shadow': 0,
  'no-unused-expressions': 0,
  'no-unused-vars': 0,
  'no-use-before-define': 0,
  'no-useless-constructor': 0,
  quotes: 0,
};

const typescriptRules = {
  ...disabledEslintRules,
  '@typescript-eslint/adjacent-overload-signatures': 2,
  '@typescript-eslint/ban-ts-comment': 1,
  '@typescript-eslint/ban-types': 2,
  '@typescript-eslint/default-param-last': 2,
  '@typescript-eslint/explicit-module-boundary-types': 2,
  '@typescript-eslint/init-declarations': [2, 'always'],
  '@typescript-eslint/lines-between-class-members': [2, 'always'],
  '@typescript-eslint/no-array-constructor': 2,
  '@typescript-eslint/no-dupe-class-members': 2,
  '@typescript-eslint/no-duplicate-imports': 2,
  '@typescript-eslint/no-empty-function': 2,
  '@typescript-eslint/no-empty-interface': 2,
  '@typescript-eslint/no-explicit-any': 1,
  '@typescript-eslint/no-extra-non-null-assertion': 2,
  '@typescript-eslint/no-inferrable-types': 2,
  '@typescript-eslint/no-invalid-this': 2,
  '@typescript-eslint/no-loop-func': 2,
  '@typescript-eslint/no-loss-of-precision': 2,
  '@typescript-eslint/no-misused-new': 2,
  '@typescript-eslint/no-namespace': 2,
  '@typescript-eslint/no-non-null-asserted-optional-chain': 2,
  '@typescript-eslint/no-non-null-assertion': 1,
  '@typescript-eslint/quotes': [
    2,
    'single',
    { avoidEscape: true, allowTemplateLiterals: true },
  ],
  '@typescript-eslint/no-redeclare': 2,
  '@typescript-eslint/no-shadow': 2,
  '@typescript-eslint/no-this-alias': 2,
  '@typescript-eslint/no-unused-expressions': 2,
  '@typescript-eslint/no-unused-vars': 2,
  '@typescript-eslint/no-use-before-define': 2,
  '@typescript-eslint/no-useless-constructor': 2,
  '@typescript-eslint/no-var-requires': 2,
  '@typescript-eslint/prefer-as-const': 2,
  '@typescript-eslint/prefer-namespace-keyword': 2,
  '@typescript-eslint/triple-slash-reference': 2,
};

export default typescriptRules;
