name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  setup:
    name: Build, Test and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Calculate Test Coverage
        run: npm run coverage

      - name: Validate Code
        run: npm run validate
