name: Commitlint Config Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/commitlint/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/commitlint

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint Files
        run: npm run lint

      - name: Validate Types
        run: npm run type

      - name: Run Tests
        run: npm run coverage

      - name: Build Package
        run: npm run build
