name: Commitlint

on:
  pull_request:
    paths:
      - 'packages/commitlint/**'

jobs:
  setup:
    name: Build, Test and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Run Tests
        run: yarn test --scope @deanacus/commitlint-config

      - name: Validate Types
        run: yarn type --scope @deanacus/commitlint-config

      - name: Validate Code Formatting
        run: yarn style --scope @deanacus/commitlint-config

      - name: Validate Code Standards
        run: yarn lint
