name: Eslint

on:
  pull_request:
    paths:
      - 'packages/eslint/**'

jobs:
  setup:
    name: Build, Test and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn

      - name: Build Package
        run: yarn build

      - name: Validate Code
        run: yarn validate --scope @deanacus/eslint-config