name: Eslint Config

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/eslint/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/eslint

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Lint Files
        run: npm run lint

      - name: Validate Types
        run: npm run type
