name: Prettier Config

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/prettier/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Dependencies
        run: yarn install

      - name: Lint Files
        run: yarn lint

      - name: Validate Types
        run: yarn type

      - name: Build Package
        run: yarn build