name: Prettier Config

on:
  pull_request:
    paths:
      - 'packages/prettier/**'

jobs:
  setup:
    name: Build, Test and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn

      - name: Build Package
        run: yarn build

      - name: Calculate Test Coverage
        run: yarn test --scope @deanacus/prettier-config

      - name: Validate Code
        run: yarn validate --scope @deanacus/prettier-config